language: node_js
node_js:
  - "5"

services:
  - docker

before_script:
  - npm i

script:
  - npm test

after_success:
  - npm run build --production
  - npm prune --production
  - docker build -t activatedgeek/react-node-starter:latest .
